### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jain-anshika**
I hope you like it! If you want any more updates please tell me!!

### CODE REVIEW

**Comment by therealdhrxv** [comment]
It's really great @jain-anshika , loved it. Just one thing - Could you please remove the license part at the end since I'll not be adding any official license to this repo.

**Comment by jain-anshika** [comment]
> It's really great @jain-anshika , loved it. Just one thing - Could you please remove the license part at the end since I'll not be adding any official license to this repo.

sure

**Comment by therealdhrxv** [comment]
Just one last thing @jain-anshika , before cloning the repo you'll have to fork it right ... could you also just mention that as the first step and then cloning as the second step and so on ... like I really wanted to keep the setting up process very easy for all beginners out there.

**Comment by jain-anshika** [comment]
> Just one last thing @jain-anshika , before cloning the repo you'll have to fork it right ... could you also just mention that as the first step and then cloning as the second step and so on ... like I really wanted to keep the setting up process very easy for all beginners out there.

**I wrote these very easy and basic steps**:-

1. Fork the repository on GitHub.

2. Clone your forked repository to your local machine:

   ```bash
   git clone https://github.com/your-username/awesome-links.git
   cd awesome-links
   ```

3. Create a new branch for your feature or bug fix:

   ```bash
   git checkout -b feature/my-new-feature
   ```

4. Make your changes and commit them:

   ```bash
   git commit -m "Add a new feature"
   ```

5. Push your changes to your fork on GitHub:

   ```bash
   git push origin feature/my-new-feature
   ```

6. Create a pull request from your forked repository to the original repository.

7. Describe your changes and submit the pull request.

**Comment by therealdhrxv** [comment]
Thank you for your contributions @jain-anshika 🤝

**Pull request merged**
